// projects/CED/web_client/src/App.vue
<!--
Copyright 2026 Rinat Ishmaev

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<template>
  <router-view />
</template>

<script setup lang="ts">
import { watch } from "vue";
import { useThemeStore } from "./store/theme";

const themeStore = useThemeStore();

watch(
  () => [themeStore.themeId, themeStore.darkMode] as const,
  () => themeStore.applyLocal(),
  { immediate: true },
);
</script>

// projects/impossible-travel/apps/web/app/page.tsx
// Copyright 2026 Rinat Ishmaev
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { redirect } from "next/navigation";

export default function Home() {
  redirect("/dashboard");
}
